import '../styles/globals.css';
import localFont from 'next/font/local';
import { Familjen_Grotesk } from 'next/font/google';
import { cn } from '@/lib/utils';
import { ReactNode } from 'react';
import ThemeProvider from '@/components/layout/Providers/ThemeProvider';

const grotesk = Familjen_Grotesk({
  weight: ['400', '500', '600', '700'],
  style: ['italic', 'normal'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-grotesk',
});

const builtTitling = localFont({
  src: [
    {
      path: '../public/fonts/BuiltTitlingBold.otf',
      weight: '700',
    },
    {
      path: '../public/fonts/BuiltTitlingSemibold.otf',
      weight: '600',
    },
    {
      path: '../public/fonts/BuiltTitlingRegular.otf',
      weight: '500',
    },
  ],
  display: 'swap',
  variable: '--font-titling',
});

export const metadata = {
  title: 'Nueva Claudinessa',
  description: 'Generated by create next app',
};

process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en'>
      <body id='body' className={cn(builtTitling?.variable, grotesk?.variable)}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
