import '../styles/globals.css';
import localFont from 'next/font/local';
import { Poppins } from 'next/font/google';
import Providers from '@/Layout/Theme/providers';

const poppins = Poppins({
  weight: ['400', '500', '700'],
  style: ['italic', 'normal'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
});

const builtTitling = localFont({
  src: [
    {
      path: '../public/fonts/BuiltTitlingBold.otf',
      weight: '700',
    },
    {
      path: '../public/fonts/BuiltTitlingSemibold.otf',
      weight: '600',
    },
  ],
  display: 'swap',
  variable: '--font-built-titling',
});

export const metadata = {
  title: 'Nueva Claudinessa',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        id='body'
        className={`${builtTitling.variable} ${poppins.variable}`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
